/* 
 * Copyright 2009 junithelper.org. 
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at 
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
 * either express or implied. See the License for the specific language 
 * governing permissions and limitations under the License. 
 */
package org.junithelper.plugin;

/**
 * STR<br>
 * <br>
 * String constant values.<br>
 * 
 * @author Kazuhiro Sera
 * @version 1.0
 */
public interface STR
{

	/**
	 * Windows OS directory separator
	 */
	public static final String WINDOWS_DIR_SEP = "\\\\";

	/**
	 * Default directory separator
	 */
	public static final String DIR_SEP = "/";

	/**
	 * Empty String
	 */
	public static final String EMPTY = "";

	/**
	 * Comma
	 */
	public static final String COMMA = ",";

	/**
	 * Dot
	 */
	public static final String DOT = ".";

	/**
	 * Asterisk
	 */
	public static final String ASTERISK = "*";

	/**
	 * Carriage return
	 */
	public static final String CARRIAGE_RETURN = "\r";

	/**
	 * Line feed
	 */
	public static final String LINE_FEED = "\n";

	/**
	 * Java file extension
	 */
	public static final String JAVA_EXP = ".java";

	/**
	 * Properties file extension
	 */
	public static final String PROPERTIES_EXP = ".properties";

	/**
	 * The suffix of test case name
	 */
	public static final String SUFFIX_OF_TESTCASE = "Test";

	/**
	 * The path to store developing sources
	 */
	public static final String SRC_MAIN_JAVA = Activator.getDefault()
			.getPreferenceStore().getString(STR.Preference.Common.SRC_MAIN_PATH);
	/**
	 * The path to store testing sources
	 */
	public static final String SRC_TEST_JAVA = Activator.getDefault()
			.getPreferenceStore().getString(STR.Preference.Common.SRC_TEST_PATH);

	/**
	 * Auto generated todo message
	 */
	public static final String AUTO_GEN_MSG_TODO = " TODO auto-generated by JUnit Helper.";

	/**
	 * Regular expressions
	 * 
	 * @author Kazuhiro Sera
	 */
	public static class RegExp
	{
		/**
		 * Dot
		 */
		public static final String DOT = "\\.";

		/**
		 * Not white/space values not required
		 */
		public static final String NOT_S_NOREQUIRED = "[^\\s]*?";

		/**
		 * Not white/space values required
		 */
		public static final String NOT_S_REQUIRED = "[^\\s]+?";

		/**
		 * While/space not required
		 */
		public static final String WHITE_AND_SPACE = "\\s*";

		/**
		 * Java file extension
		 */
		public static final String JAVA_EXP = "\\.java";

	}

	/**
	 * Dialog messages
	 * 
	 * @author Kazuhiro Sera
	 */
	public static class Dialog
	{
		public static class Common
		{
			/**
			 * Title
			 */
			public static final String TITLE = "JUnit Helper";

			/**
			 * Confirm to execute
			 */
			public static final String EXCUTE_QUESTION = "Execute OK?";
			/**
			 * Select required
			 */
			public static final String REQUIRED = "Please select target.";
			/**
			 * Select only one
			 */
			public static final String SELECT_ONLY_ONE = "Please select only one target.";

			/**
			 * Already file exists
			 */
			public static final String ALREADY_EXIST = "Already exist.";

			/**
			 * File does not exist
			 */
			public static final String NOT_EXIST = "Not exist.";

			/**
			 * Confirm to proceed
			 */
			public static final String CONFIRM_PROCEED = "Proceed OK?";

			/**
			 * Setting not to create new file
			 */
			public static final String NOT_CREATE_NEW_FILE = "Test case file does not exist."
					+ STR.LINE_FEED
					+ "If you want to generate, please alter preferences.";

			/**
			 * Confirm to create new file
			 */
			public static final String COMFIRM_CREATE_NEW_FILE = "Create new test case file?";

			/**
			 * Error occurred when refreshing resource
			 */
			public static final String RESOURCE_REFRESH_ERROR = "Resource refresh error!";

			/**
			 * Select java extension file
			 */
			public static final String SELECT_JAVA_FILE = "Please select java source file(*.java).";

			/**
			 * Select Test.java extension file
			 */
			public static final String NOT_TEST_CLASS = "Please select test class file.";

		}
	}

	/**
	 * Preferences
	 * 
	 * @author Kazuhiro Sera
	 */
	public static class Preference
	{

		/**
		 * Select language
		 */
		// TODO
		public static final String LANG = "Language";

		/**
		 * Common
		 * 
		 * @author Kazuhiro Sera
		 */
		public static class Common
		{
			/**
			 * Description
			 */
			public static final String DESCRIPTION = "JUnit Helper Prefernces.";
			/**
			 * Main Source Folder
			 */
			public static final String SRC_MAIN_PATH = "Main Source Folder";
			/**
			 * Test Source Folder
			 */
			public static final String SRC_TEST_PATH = "Test Source Folder";
		}

		public static class TestClassGen
		{

			/**
			 * Enable test methods gen
			 */
			public static final String ENABLE = "Test Class Auto Generate";

			/**
			 * Class To Extend
			 */
			public static final String CLASS_TO_EXTEND = "Class To Extend";
		}

		public static class TestMethodGen
		{
			/**
			 * Enable test methods gen
			 */
			public static final String ENABLE = "Test Method Auto Generate";
			/**
			 * Delimiter to test method name
			 */
			public static final String DELIMITER = "Delimiter";

			/**
			 * Enable includes method args in test method name
			 */
			public static final String ARGS = "Includes Method Args";
			/**
			 * Args prefix
			 */
			public static final String ARGS_PREFIX = "Args Prefix";
			/**
			 * Args delimiter
			 */
			public static final String ARGS_DELIMITER = "Args Delimiter";

			/**
			 * Enable includes method return in test method name
			 */
			public static final String RETURN = "Includes Method Return";
			/**
			 * Return prefix
			 */
			public static final String RETURN_PREFIX = "Return Prefix";
			/**
			 * Return delimiter
			 */
			public static final String RETURN_DELIMITER = "Return Delimiter";

			/**
			 * Exclude accessors
			 */
			public static final String EXLCUDES_ACCESSORS = "Exculdes Accessors(setter/getter)";
			/**
			 * Generate sample implementation to test methods
			 */
			public static final String METHOD_SAMPLE_IMPLEMENTATION = "Generate Sample Implementation";
		}
	}
}
