#!/bin/sh 
dir=`dirname $0`
java \
    -Djunithelper.configProperties=${dir}/junithelper-config.properties \
    -Djunithelper.extensionConfigXML=${dir}/junithelper-extension.xml \
    -jar ${dir}/junithelper-core-1.11.jar \
    $1 \
    $2

