/* 
 * Copyright 2009-2010 junithelper.org. 
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at 
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
 * either express or implied. See the License for the specific language 
 * governing permissions and limitations under the License. 
 */
package org.junithelper.plugin.constant;

/**
 * StrConst<br>
 * <br>
 * String constant values.<br>
 * 
 * @author Kazuhiro Sera <seratch@gmail.com>
 * @version 1.0
 */
public interface StrConst {

	/**
	 * Windows OS directory separator
	 */
	public static final String windowsDirSep = "\\\\";

	/**
	 * Default directory separator
	 */
	public static final String dirSep = "/";

	/**
	 * Empty String
	 */
	public static final String empty = "";

	/**
	 * Space
	 */
	public static final String space = " ";

	/**
	 * Space
	 */
	public static final String tab = "\t";

	/**
	 * Comma
	 */
	public static final String comma = ",";

	/**
	 * Dot
	 */
	public static final String dot = ".";

	/**
	 * Asterisk
	 */
	public static final String asterisk = "*";

	/**
	 * Carriage return
	 */
	public static final String carriageReturn = "\r";

	/**
	 * Line feed
	 */
	public static final String lineFeed = "\n";

	/**
	 * Java file extension
	 */
	public static final String javaFileExp = ".java";

	/**
	 * Properties file extension
	 */
	public static final String propertiesFileExp = ".properties";

	/**
	 * The suffix of test case name
	 */
	public static final String suffixOfTestcase = "Test";

	/**
	 * Auto generated todo message
	 */
	public static final String autoGenTodoMessage = " TODO auto-generated by JUnit Helper.";

	public static final String testMethodPrefix4Version3 = "test_";

}
